force-app/main/default/objects/sales_areas__c/sales_areas__c.object-meta.xml
<CustomObject>
    <label>sales areas</label>
    <nameField>
        <label>sales areas Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sales areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sales_areas__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>sales areas</relationshipLabel>
    <relationshipName>sales_areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sales_areas__c/fields/Sales_Area__c.field-meta.xml
<CustomField>
    <fullName>Sales_Area__c</fullName>
    <label>Sales Codes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
            </value>
            <value>
                <fullName>002</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesCodeAccountHAndler.cls
public with sharing class SalesCodeAccountHandler
{
    public static void SalesCodeInsert(List<Sales_areas__C> lstSalesAreaCodes) 
    {
       Set<id> SalesCodeIds = new Set<id>();
       try
       {
        for(Sales_areas__c sc :lstSalesAreaCodes)
        {
            if(sc.account__c!=null)
            {
                SalesCodeIds.add(sc.account__c);
            }
        }
        if(!SalesCodeIds.isEmpty())
        {
            List<Account> lstAccounts = [select id,Sales_Area_Codes__c, (select id,Sales_Area__c from Sales_areas__r) from account where id in :SalesCodeIds];
            
            if(!lstAccounts.isEmpty())
            {
                for(Account acc:lstAccounts)
                {
                    if(acc.Sales_Areas__r.size()>=1)
                    {
                         acc.Sales_Area_Codes__c=' ';
                         for(Sales_Areas__c sca: acc.Sales_Areas__r)
  						 {
   							acc.Sales_Area_Codes__c+=sca.Sales_Area__c+';';
   						 }
   							   
                   	}
                }
                update lstAccounts;
            }
        }
        }
        Catch(Exception e)
        {
            system.debug('Exception error is '+e.getMessage());
            system.debug('Exception error is '+e.getLineNumber());
        }
    }
}